FROM golang:1.26-alpine AS base
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .

FROM base AS build
RUN go build -o /out/dotmgr ./cmd/dotmgr

FROM scratch AS artifact
COPY --from=build /out/dotmgr /dotmgr
